FROM selvan/phoenix:1.0.2

MAINTAINER selvan <p.thamarai@gmail.com>

ADD . /code
WORKDIR /code
RUN mix do deps.get, deps.compile
RUN npm install

ENV MIX_ENV prod
RUN mix compile

RUN export PATH=/usr/local/bin:$PATH
RUN node_modules/brunch/bin/brunch build --production

CMD mix phoenix.server

EXPOSE  4000
