FROM selvan/phoenix:1.0.2

MAINTAINER selvan <p.thamarai@gmail.com>

ADD . /code
VOLUME /code
WORKDIR /code

RUN mix do deps.get, deps.compile
RUN npm install

RUN export PATH=/usr/local/bin:$PATH

CMD mix phoenix.server

EXPOSE  4000
