web:
  build: .
  dockerfile: Dockerfile.dev
  ports:
    - "4000:4000"
  volumes:
    - .:/code    
  links:
    - db
db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
